name: stability-preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.11.8
  - pandas=2.2.1
  - numpy=1.26.4
  - scipy=1.13
  - scikit-learn=1.4.1.post1
  - matplotlib=3.8.4
  - seaborn=0.13.0
  - jupyter=1.0.0
  - ipykernel=6.29.3
  - caiman=1.11
  - black=24.3.0
